export function dashboardSummary(reps = []) {
  const tracked = reps.filter((rep) => rep.contract?.currentContract && rep.contract?.currentTier);
  const active = tracked.filter((rep) => rep.contract.daysRemaining > 0);
  return {
    activeReps: active.length,
    tier1: active.filter((rep) => rep.contract.currentTier === 1).length,
    renewalsDueSoon: active.filter((rep) => rep.contract.daysRemaining <= 30).length,
    expired: tracked.filter((rep) => rep.contract.daysRemaining <= 0).length,
  };
}

export function attentionContracts(reps = []) {
  return reps
    .filter((rep) => rep.contract?.currentContract && rep.contract.daysRemaining <= 30)
    .sort((a, b) => a.contract.daysRemaining - b.contract.daysRemaining
      || String(a.name || '').localeCompare(String(b.name || '')));
}

export function upcomingContracts(reps = []) {
  return reps
    .filter((rep) => rep.contract?.currentContract
      && rep.contract.daysRemaining >= 31
      && rep.contract.daysRemaining <= 90)
    .sort((a, b) => a.contract.daysRemaining - b.contract.daysRemaining
      || String(a.name || '').localeCompare(String(b.name || '')));
}

export function contractStatus(daysRemaining) {
  if (daysRemaining <= 0) return { key: 'expired', label: 'Expired', detail: 'Renewal required' };
  if (daysRemaining <= 7) return { key: 'action', label: 'Action Required', detail: 'Renewal is urgent' };
  if (daysRemaining <= 30) return { key: 'renewal', label: 'Renewal Soon', detail: 'Renewal is approaching' };
  return { key: 'active', label: 'Active', detail: 'Contract is current' };
}

export function primaryAgreementName(envelope = {}) {
  return envelope.primaryDocumentName
    || envelope.documents?.find((document) => document.classification === 'signed_document')?.name
    || envelope.documents?.[0]?.name
    || 'Completed Agreement';
}

export function documentPresentation(classification) {
  if (classification === 'signed_document') {
    return { key: 'signed', badge: 'Signed Document', heading: 'Employment Agreement' };
  }
  if (classification === 'certificate') {
    return { key: 'certificate', badge: 'Certificate', heading: 'DocuSign Certificate' };
  }
  return { key: 'supplemental', badge: 'Supplemental', heading: 'Supplemental File' };
}

export function avatarInitials(name = '') {
  const parts = String(name).trim().split(/\s+/).filter(Boolean);
  if (!parts.length) return 'CI';
  return `${parts[0][0] || ''}${parts.length > 1 ? parts.at(-1)[0] : ''}`.toUpperCase();
}

export function formatFileSize(bytes) {
  const value = Number(bytes);
  if (!Number.isFinite(value) || value < 0) return '';
  if (value < 1024) return `${value} B`;
  if (value < 1024 * 1024) return `${Math.round(value / 1024)} KB`;
  return `${(value / (1024 * 1024)).toFixed(value >= 10 * 1024 * 1024 ? 0 : 1)} MB`;
}

export const documentsPage = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="theme-color" content="#10281d">
  <title>Contract Management · Capital Infusion</title>
  <style>
    :root{color-scheme:light;--ink:#18231d;--muted:#68746d;--line:#dfe5e1;--line-strong:#cfd9d3;--paper:#fff;--canvas:#f5f7f5;--brand:#176542;--brand-dark:#104a31;--brand-soft:#e6f3eb;--amber:#875918;--amber-soft:#fff4dd;--red:#a03831;--red-soft:#fff0ee;--neutral:#eef1ef;--shadow-sm:0 1px 2px rgb(14 42 27/.05);--topbar-height:64px}
    *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--canvas);color:var(--ink);font:14px/1.5 Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}button,input,select{font:inherit}[hidden]{display:none!important}a{color:inherit}
    .skip-link{position:fixed;left:16px;top:-64px;z-index:100;background:var(--brand);color:#fff;padding:10px 14px;border-radius:8px;font-weight:700}.skip-link:focus{top:12px}
    .app-shell,.app-frame{min-height:100vh}.topbar{position:sticky;top:0;z-index:30;height:var(--topbar-height);display:flex;align-items:center;padding:0 28px;background:rgb(255 255 255/.94);border-bottom:1px solid var(--line);backdrop-filter:blur(12px)}.topbar-context{display:flex;align-items:center;gap:9px}.topbar-context strong{font-size:14px}.topbar-context span{color:var(--muted);font-size:12px}.topbar-divider{width:1px;height:16px;background:var(--line)}
    .content{width:100%;max-width:1248px;margin:0 auto;padding:30px 34px 72px}.page-header{display:flex;align-items:flex-end;justify-content:space-between;gap:24px;margin-bottom:24px}.page-title{margin:5px 0 5px;font-size:clamp(25px,3vw,34px);font-weight:760;letter-spacing:-.025em;line-height:1.15}.page-description{max-width:650px;color:var(--muted);font-size:14px}.breadcrumbs{display:flex;align-items:center;gap:7px;color:var(--muted);font-size:12px}.breadcrumbs a{color:var(--brand);font-weight:700;text-decoration:none}.breadcrumbs a:hover{text-decoration:underline}.breadcrumb-separator{color:#a4afa8}
    .profile-title{display:flex;align-items:center;gap:14px;margin-top:12px}.avatar{display:grid;place-items:center;flex:none;width:38px;height:38px;border-radius:10px;background:var(--brand-soft);color:var(--brand-dark);font-size:12px;font-weight:850;letter-spacing:.02em}.avatar.large{width:48px;height:48px;border-radius:12px;font-size:15px}.profile-name{margin:0;font-size:25px;font-weight:780;letter-spacing:-.02em}.profile-email{color:var(--muted)}.profile-badges{display:flex;flex-wrap:wrap;gap:7px;margin-top:8px}
    .stat-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin-bottom:18px}.stat-card{display:grid;grid-template-columns:auto 1fr;gap:12px;align-items:start;min-height:102px;padding:16px;background:var(--paper);border:1px solid var(--line);border-radius:10px;box-shadow:var(--shadow-sm)}.stat-icon{display:grid;place-items:center;width:32px;height:32px;border-radius:8px;background:var(--brand-soft);color:var(--brand)}.stat-icon svg{width:16px;height:16px}.stat-label{color:var(--muted);font-size:10px;font-weight:820;letter-spacing:.09em;text-transform:uppercase}.stat-value{display:block;margin-top:5px;font-size:25px;font-weight:800;line-height:1;color:var(--ink)}.stat-note{display:block;margin-top:7px;color:var(--muted);font-size:11px}
    .dashboard-columns{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px;margin-bottom:18px}.panel{background:var(--paper);border:1px solid var(--line);border-radius:10px;box-shadow:var(--shadow-sm);overflow:hidden}.panel-header{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:15px 17px;border-bottom:1px solid var(--line)}.panel-title{margin:0;font-size:14px;font-weight:780}.panel-description{margin-top:2px;color:var(--muted);font-size:11px}.panel-body{padding:0}.panel-body.padded{padding:15px 17px}.panel + .panel{margin-top:16px}
    .status-badge{display:inline-flex;align-items:center;gap:5px;border-radius:999px;padding:3px 8px;font-size:10px;font-weight:800;line-height:1.4;white-space:nowrap}.status-badge:before{content:"";width:5px;height:5px;border-radius:50%;background:currentColor}.status-active,.status-tier,.status-signed,.status-contract{background:var(--brand-soft);color:var(--brand-dark)}.status-renewal,.status-certificate{background:var(--amber-soft);color:var(--amber)}.status-action,.status-expired{background:var(--red-soft);color:var(--red)}.status-neutral,.status-supplemental{background:var(--neutral);color:#58645d}
    .data-list{display:grid}.data-row{display:grid;grid-template-columns:minmax(0,1fr) auto auto;gap:16px;align-items:center;min-height:70px;padding:13px 16px;border-top:1px solid var(--line);text-decoration:none;transition:background .15s ease}.data-row:first-child{border-top:0}.data-row:hover{background:#f8faf8}.data-row-main{display:flex;align-items:center;gap:12px;min-width:0}.data-row-copy{min-width:0}.data-row-title{font-weight:760;overflow-wrap:anywhere}.data-row-subtitle{margin-top:2px;color:var(--muted);font-size:12px}.data-row-meta{display:flex;align-items:center;justify-content:flex-end;gap:7px;flex-wrap:wrap;color:var(--muted);font-size:11px}.data-row-tail{display:flex;align-items:center;gap:13px;color:var(--muted);font-size:11px;white-space:nowrap}.chevron{color:var(--brand);font-size:19px;line-height:1}
    .attention-row{grid-template-columns:minmax(0,1fr) auto}.attention-time{display:flex;align-items:center;gap:9px}.attention-time strong{color:var(--ink);font-size:12px}.urgency-bar{width:3px;align-self:stretch;border-radius:4px;background:var(--amber)}.attention-row.is-urgent .urgency-bar{background:var(--red)}
    .empty-state{display:flex;align-items:center;gap:11px;min-height:76px;padding:16px;color:var(--muted)}.empty-icon{display:grid;place-items:center;width:32px;height:32px;border-radius:8px;background:var(--neutral);color:#718077}.empty-icon svg{width:16px;height:16px}.error{padding:16px;border:1px solid #efc6c2;border-radius:10px;background:var(--red-soft);color:var(--red)}
    .section-space{margin-top:18px}.toolbar{display:flex;gap:9px}.field{position:relative;display:flex;align-items:center}.field.search{flex:1}.field-icon{position:absolute;left:11px;width:16px;height:16px;color:#87928b;pointer-events:none}.control{width:100%;height:38px;border:1px solid var(--line-strong);border-radius:8px;background:#fff;color:var(--ink);outline:none}.control:hover{border-color:#b5c3ba}.control:focus{border-color:#65a17e;box-shadow:0 0 0 3px rgb(53 139 91/.13)}input.control{padding:8px 11px 8px 36px}select.control{min-width:175px;padding:7px 32px 7px 11px}
    .tabs{display:flex;gap:3px;margin:0 0 16px;padding:4px;background:#e9eeeb;border-radius:9px;width:max-content;max-width:100%}.rep-type-tabs{margin:12px 16px}.tab{min-width:108px;padding:8px 12px;border:0;border-radius:7px;background:transparent;color:var(--muted);font-weight:700;cursor:pointer}.tab:hover{color:var(--ink)}.tab[aria-selected="true"]{background:#fff;color:var(--brand-dark);box-shadow:var(--shadow-sm)}.tab-panel:focus{outline:none}
    .contract-stats{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));border-bottom:1px solid var(--line)}.contract-stat{padding:17px;border-right:1px solid var(--line)}.contract-stat:last-child{border-right:0}.contract-stat-label{color:var(--muted);font-size:10px;font-weight:800;letter-spacing:.08em;text-transform:uppercase}.contract-stat-value{margin-top:5px;font-size:16px;font-weight:780}.contract-status{display:flex;align-items:center;justify-content:space-between;gap:20px;margin:14px;padding:14px 15px;border-radius:8px;background:var(--brand-soft)}.contract-status.status-renewal{background:var(--amber-soft)}.contract-status.status-action,.contract-status.status-expired{background:var(--red-soft)}.contract-status strong{font-size:13px}.contract-status-copy{color:var(--muted);font-size:11px}
    .history-row{grid-template-columns:minmax(0,1fr) auto}.history-tier{display:flex;align-items:center;gap:10px}.history-dates{margin-top:3px;color:var(--muted);font-size:12px}.agreement-type{margin-top:4px;color:var(--muted);font-size:11px}.agreement-type strong{color:var(--brand);font-weight:750}
    .document-row{grid-template-columns:minmax(0,1fr) auto;min-height:88px}.file-mark{display:grid;place-items:center;width:38px;height:44px;border:1px solid #cfe0d5;border-radius:7px;background:#f2f8f4;color:var(--brand-dark);font-size:9px;font-weight:900}.document-row.is-signed{background:#fbfdfb}.document-row.is-signed .data-row-title{font-size:14px}.document-meta{display:flex;align-items:center;gap:7px;margin-top:5px;color:var(--muted);font-size:11px}.document-actions{display:flex;gap:7px}.button{display:inline-flex;align-items:center;justify-content:center;min-height:34px;padding:7px 11px;border:1px solid var(--brand);border-radius:7px;background:#fff;color:var(--brand);font-weight:750;text-decoration:none}.button:hover{background:var(--brand-soft)}.button.primary{background:var(--brand);color:#fff}.button.primary:hover{background:var(--brand-dark)}
    .details-disclosure{margin-top:16px;background:#fff;border:1px solid var(--line);border-radius:9px;overflow:hidden}.details-disclosure summary{display:flex;align-items:center;gap:8px;padding:12px 15px;color:var(--brand-dark);font-size:12px;font-weight:780;cursor:pointer}.details-disclosure summary:before{content:"›";font-size:18px;line-height:1;transition:transform .15s ease}.details-disclosure[open] summary:before{transform:rotate(90deg)}.details-disclosure[open] summary{border-bottom:1px solid var(--line)}.metadata-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:15px;padding:15px}.metadata-label{color:var(--muted);font-size:10px;font-weight:800;letter-spacing:.07em;text-transform:uppercase}.metadata-value{margin-top:3px;font-size:12px;font-weight:650;overflow-wrap:anywhere}.technical{font:11px/1.5 ui-monospace,SFMono-Regular,Consolas,monospace;color:var(--muted)}
    .button:focus-visible,.data-row:focus-visible,.tab:focus-visible,.details-disclosure summary:focus-visible,.breadcrumbs a:focus-visible{outline:3px solid #6db28b;outline-offset:2px}.sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}
    @media(max-width:980px){.stat-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.contract-stats{grid-template-columns:repeat(2,minmax(0,1fr))}.contract-stat{border-bottom:1px solid var(--line)}.contract-stat:nth-child(2n){border-right:0}.contract-stat:last-child{border-bottom:0}.dashboard-columns{grid-template-columns:1fr}}
    @media(max-width:820px){.topbar{padding:0 18px}.content{padding:24px 18px 58px}}
    @media(max-width:620px){.page-header{display:block}.page-title{font-size:27px}.stat-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.stat-card{display:block;min-height:96px}.stat-icon{margin-bottom:11px}.toolbar{display:grid}.field.search{width:100%}select.control{width:100%}.data-row,.attention-row,.document-row{grid-template-columns:minmax(0,1fr) auto;gap:10px}.data-row-meta{grid-column:1/3;justify-content:flex-start;margin-left:50px}.data-row-tail{grid-column:1/3;justify-content:space-between;margin-left:50px}.attention-row .data-row-tail{grid-column:2;margin-left:0}.tabs{width:100%;overflow-x:auto}.rep-type-tabs{width:calc(100% - 32px)}.tab{min-width:max-content;flex:1}.document-row{display:block}.document-actions{display:grid;grid-template-columns:1fr 1fr;margin-top:14px}.button{width:100%}.contract-status{display:block}.contract-status>div+div{margin-top:9px}.metadata-list{grid-template-columns:1fr}.profile-title{align-items:flex-start}.profile-name{font-size:22px}}
    @media(max-width:390px){.content{padding-inline:12px}.stat-grid{grid-template-columns:1fr 1fr;gap:8px}.stat-card{padding:13px}.stat-note{display:none}.topbar{padding-inline:12px}}
  </style>
</head>
<body>
  <a class="skip-link" href="#main-content">Skip to main content</a>
  <div class="app-shell">
    <div class="app-frame">
      <header class="topbar"><div class="topbar-context"><strong>Contract Management</strong><span class="topbar-divider" aria-hidden="true"></span><span>Capital Infusion</span></div></header>
      <main class="content" id="main-content" tabindex="-1"><div id="app"><div class="empty-state" role="status">Loading contract workspace…</div></div></main>
    </div>
  </div>
<script>
${dashboardSummary}
${attentionContracts}
${upcomingContracts}
${contractStatus}
${primaryAgreementName}
${documentPresentation}
${avatarInitials}
${formatFileSize}
const app=document.querySelector('#app');
const esc=(value='')=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=value=>value?new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'Unknown';
const dateOnly=value=>value?new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeZone:'UTC'}).format(new Date(value)):'Unknown';
async function api(path){const response=await fetch(path);const body=await response.json();if(!response.ok)throw new Error(body.error||'Request failed');return body}
function Icon(name){const paths={chart:'<path d="M4 19V9m6 10V5m6 14v-7m4 7H2"/>',tier:'<path d="M4 18h16M6 18v-4h4v4m0-4V9h4v9m0-9V5h4v13"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v6l4 2"/>',alert:'<path d="M12 3 2.8 20h18.4z"/><path d="M12 9v5m0 3h.01"/>',empty:'<circle cx="12" cy="12" r="9"/><path d="M8 12h8"/>',search:'<circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/>'};return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+(paths[name]||paths.empty)+'</svg>'}
function Avatar(name,size){return '<span class="avatar'+(size?' '+size:'')+'" aria-hidden="true">'+esc(avatarInitials(name))+'</span>'}
function StatusBadge(label,key){return '<span class="status-badge status-'+key+'">'+esc(label)+'</span>'}
function Breadcrumbs(items){return '<nav class="breadcrumbs" aria-label="Breadcrumb">'+items.map((item,index)=>(index?'<span class="breadcrumb-separator" aria-hidden="true">/</span>':'')+(item.href?'<a href="'+item.href+'">'+esc(item.label)+'</a>':'<span aria-current="page">'+esc(item.label)+'</span>')).join('')+'</nav>'}
function PageHeader(options){const identity=options.identity?'<div class="profile-title">'+Avatar(options.identity.name,'large')+'<div><h1 class="profile-name">'+esc(options.identity.name)+'</h1><div class="profile-email">'+esc(options.identity.email||'')+'</div>'+(options.identity.badges||'')+'</div></div>':'';return '<header class="page-header"><div>'+(options.breadcrumbs||'')+(options.eyebrow?'<div class="breadcrumbs">'+esc(options.eyebrow)+'</div>':'')+(identity||'<h1 class="page-title">'+esc(options.title)+'</h1><div class="page-description">'+esc(options.description||'')+'</div>')+'</div>'+(options.actions||'')+'</header>'}
function SectionHeader(title,description,tools){return '<div class="panel-header"><div><h2 class="panel-title">'+esc(title)+'</h2>'+(description?'<div class="panel-description">'+esc(description)+'</div>':'')+'</div>'+(tools||'')+'</div>'}
function Panel(options){return '<section class="panel'+(options.className?' '+options.className:'')+'"'+(options.id?' id="'+options.id+'"':'')+(options.labelledBy?' aria-labelledby="'+options.labelledBy+'"':'')+'>'+(options.header||'')+'<div class="panel-body'+(options.padded?' padded':'')+'">'+options.body+'</div></section>'}
function StatCard(label,value,note,icon){return '<article class="stat-card"><span class="stat-icon">'+Icon(icon)+'</span><div><span class="stat-label">'+esc(label)+'</span><strong class="stat-value">'+value+'</strong><span class="stat-note">'+esc(note)+'</span></div></article>'}
function EmptyState(message){return '<div class="empty-state"><span class="empty-icon">'+Icon('empty')+'</span><span>'+esc(message)+'</span></div>'}
function SearchInput(id,placeholder,label){return '<label class="sr-only" for="'+id+'">'+esc(label)+'</label><div class="field search"><span class="field-icon">'+Icon('search')+'</span><input class="control" id="'+id+'" type="search" placeholder="'+esc(placeholder)+'"></div>'}
function SelectControl(id,label,options){return '<label class="sr-only" for="'+id+'">'+esc(label)+'</label><div class="field"><select class="control" id="'+id+'">'+options.map(option=>'<option value="'+option.value+'">'+esc(option.label)+'</option>').join('')+'</select></div>'}
function PrimaryButton(label,href,ariaLabel,newWindow){return '<a class="button primary" href="'+href+'"'+(newWindow?' target="_blank" rel="noopener"':'')+' aria-label="'+esc(ariaLabel||label)+'">'+esc(label)+'</a>'}
function SecondaryButton(label,href,ariaLabel){return '<a class="button" href="'+href+'" aria-label="'+esc(ariaLabel||label)+'">'+esc(label)+'</a>'}
function DataRow(options){return '<a class="data-row'+(options.className?' '+options.className:'')+'" href="'+options.href+'" aria-label="'+esc(options.ariaLabel)+'">'+options.main+(options.meta||'')+(options.tail||'<span class="chevron" aria-hidden="true">›</span>')+'</a>'}
function remainingLabel(days){if(days===0)return 'Expires today';if(days<0)return 'Expired '+Math.abs(days)+' day'+(Math.abs(days)===1?'':'s')+' ago';return days+' day'+(days===1?'':'s')+' remaining'}
function tierTransition(contract){return contract.nextTier?'Tier '+contract.currentTier+' → Tier '+contract.nextTier:'Tier '+contract.currentTier}
function summaryMarkup(reps){const values=dashboardSummary(reps);return '<section class="stat-grid" aria-label="Contract summary">'+StatCard('Active Reps',values.activeReps,'With current contracts','chart')+StatCard('Tier 1',values.tier1,'Active first tier','tier')+StatCard('Renewals Due',values.renewalsDueSoon,'Within 30 days','clock')+StatCard('Expired',values.expired,'Renewal required','alert')+'</section>'}
function AttentionRow(rep){const contract=rep.contract;const status=contractStatus(contract.daysRemaining);const main='<div class="data-row-main"><span class="urgency-bar" aria-hidden="true"></span>'+Avatar(rep.name)+'<div class="data-row-copy"><div class="data-row-title">'+esc(rep.name)+'</div><div class="data-row-subtitle">'+esc(tierTransition(contract))+' · '+esc(dateOnly(contract.expiresAt))+'</div></div></div>';const tail='<div class="attention-time">'+StatusBadge(status.label,status.key)+'<strong>'+esc(remainingLabel(contract.daysRemaining))+'</strong><span class="chevron" aria-hidden="true">›</span></div>';return DataRow({href:'/documents/reps/'+encodeURIComponent(rep.repId),ariaLabel:'View '+rep.name+' contract',className:'attention-row '+(['expired','action'].includes(status.key)?'is-urgent':''),main,tail})}
function renewalPanels(reps){const attention=attentionContracts(reps);const upcoming=upcomingContracts(reps);const attentionPanel=Panel({header:SectionHeader('Needs Attention','Expired contracts and renewals due within 30 days.'),body:attention.length?'<div class="data-list">'+attention.map(AttentionRow).join('')+'</div>':EmptyState('No contracts currently require attention.')});const upcomingPanel=Panel({header:SectionHeader('Upcoming Renewals','Active contracts expiring in 31–90 days.'),body:upcoming.length?'<div class="data-list">'+upcoming.map(AttentionRow).join('')+'</div>':EmptyState('No upcoming renewals.')});return '<div class="dashboard-columns" id="contracts">'+attentionPanel+upcomingPanel+'</div>'}
function RepRow(rep){const contract=rep.contract;const status=contract?.currentTier?contractStatus(contract.daysRemaining):undefined;const main='<div class="data-row-main">'+Avatar(rep.name)+'<div class="data-row-copy"><div class="data-row-title">'+esc(rep.name)+'</div><div class="data-row-subtitle">'+esc(rep.email||(rep.type==='requires_resolution'?'Signer identity requires review':'No completed signer resolved'))+'</div></div></div>';const meta='<div class="data-row-meta">'+(contract?.currentTier?StatusBadge(contract.contractType||'Unknown','contract')+StatusBadge(status.label,status.key)+StatusBadge('Tier '+contract.currentTier,'tier')+'<span>Expires '+esc(dateOnly(contract.expiresAt))+'</span>':StatusBadge('No Contract','neutral'))+'</div>';const tail='<div class="data-row-tail"><span>'+rep.completedEnvelopeCount+' agreement'+(rep.completedEnvelopeCount===1?'':'s')+'</span><span class="chevron" aria-hidden="true">›</span></div>';return DataRow({href:'/documents/reps/'+encodeURIComponent(rep.repId),ariaLabel:'View '+rep.name+' contract details',main,meta,tail})}
function renderRepResults(reps){document.querySelector('#rep-results').innerHTML=reps.length?'<div class="data-list">'+reps.map(RepRow).join('')+'</div>':EmptyState('No representatives found.')}
async function dashboardPage(){const initial=await api('/api/reps?sort=recent');let contractType='all';const toolbar='<div class="toolbar">'+SearchInput('rep-search','Search representatives...','Search representatives by name or email')+SelectControl('rep-sort','Sort representatives',[{value:'recent',label:'Recent Activity'},{value:'name',label:'Name'},{value:'count',label:'Agreement Count'},{value:'expiration',label:'Contract Expiration'}])+'</div>';const typeTabs='<div class="tabs rep-type-tabs" role="tablist" aria-label="Representative contract type"><button class="tab" type="button" role="tab" aria-selected="true" aria-controls="rep-results" data-contract-type="all">All</button><button class="tab" type="button" role="tab" aria-selected="false" aria-controls="rep-results" data-contract-type="W-2">W-2</button><button class="tab" type="button" role="tab" aria-selected="false" aria-controls="rep-results" data-contract-type="1099">1099</button></div>';const repsPanel=Panel({id:'representatives',header:SectionHeader('Representatives','Review contract status and completed agreements.',toolbar),body:typeTabs+'<div id="rep-results" role="tabpanel"></div>'});app.innerHTML=PageHeader({title:'Contract Management',description:'Manage representative agreements, contract status, and renewals.'})+summaryMarkup(initial.reps)+renewalPanels(initial.reps)+repsPanel;renderRepResults(initial.reps);const load=async()=>{const query=new URLSearchParams({search:document.querySelector('#rep-search').value,sort:document.querySelector('#rep-sort').value});if(contractType!=='all')query.set('contractType',contractType);renderRepResults((await api('/api/reps?'+query)).reps)};for(const tab of document.querySelectorAll('[data-contract-type]'))tab.addEventListener('click',()=>{contractType=tab.dataset.contractType;for(const item of document.querySelectorAll('[data-contract-type]'))item.setAttribute('aria-selected',String(item===tab));load()});document.querySelector('#rep-search').addEventListener('input',load);document.querySelector('#rep-sort').addEventListener('change',load);scrollToHash()}
function Tabs(items){return '<div class="tabs" role="tablist" aria-label="Representative sections">'+items.map((item,index)=>'<button class="tab" id="tab-'+item.id+'" type="button" role="tab" aria-selected="'+(index===0?'true':'false')+'" aria-controls="panel-'+item.id+'" tabindex="'+(index===0?'0':'-1')+'" data-tab="'+item.id+'">'+esc(item.label)+'</button>').join('')+'</div>'}
function activateTab(id,focus){const tabs=[...document.querySelectorAll('[data-tab]')];if(!tabs.some(tab=>tab.dataset.tab===id))id=tabs[0]?.dataset.tab;for(const tab of tabs){const active=tab.dataset.tab===id;tab.setAttribute('aria-selected',String(active));tab.tabIndex=active?0:-1;document.querySelector('#panel-'+tab.dataset.tab).hidden=!active;if(active&&focus)tab.focus()}if(id)history.replaceState(null,'','#'+id)}
function initTabs(){const tabs=[...document.querySelectorAll('[data-tab]')];for(const tab of tabs){tab.addEventListener('click',()=>activateTab(tab.dataset.tab));tab.addEventListener('keydown',event=>{const index=tabs.indexOf(tab);let next;if(event.key==='ArrowRight')next=(index+1)%tabs.length;if(event.key==='ArrowLeft')next=(index-1+tabs.length)%tabs.length;if(event.key==='Home')next=0;if(event.key==='End')next=tabs.length-1;if(next!==undefined){event.preventDefault();activateTab(tabs[next].dataset.tab,true)}})}const requested=location.hash.slice(1);activateTab(tabs.some(tab=>tab.dataset.tab===requested)?requested:'overview')}
function CurrentContractPanel(contract){if(!contract?.currentTier)return Panel({header:SectionHeader('Current Contract','Contract lifecycle summary.'),body:EmptyState('No tracked contract is available for this representative.')});const status=contractStatus(contract.daysRemaining);const stats=[['Contract Type',contract.contractType||'Unknown'],['Tier','Tier '+contract.currentTier],['Signed',dateOnly(contract.signedAt)],['Expiration',dateOnly(contract.expiresAt)],['Next Tier',contract.nextTier?'Tier '+contract.nextTier:'—']].map(item=>'<div class="contract-stat"><div class="contract-stat-label">'+item[0]+'</div><div class="contract-stat-value">'+esc(item[1])+'</div></div>').join('');const statusPanel='<div class="contract-status status-'+status.key+'"><div><strong>Contract Status</strong><div class="contract-status-copy">'+esc(status.detail)+'</div></div><div>'+StatusBadge(status.label,status.key)+' <span class="contract-status-copy">'+esc(remainingLabel(contract.daysRemaining))+'</span></div></div>';return Panel({header:SectionHeader('Current Contract','Current tier and renewal timeline.'),body:'<div class="contract-stats">'+stats+'</div>'+statusPanel})}
function ContractHistoryPanel(contract){const history=(contract?.contracts||[]).map(item=>{const current=item.envelopeId===contract.currentContract?.envelopeId;const expired=current&&contract.daysRemaining<=0;const label=current?(expired?'Expired':'Active'):'Renewed';const key=expired?'expired':current?'active':'neutral';return '<div class="data-row history-row"><div><div class="history-tier">'+StatusBadge(item.contractType||'Unknown','contract')+StatusBadge('Tier '+item.tier,'tier')+'<strong>'+label+'</strong></div><div class="history-dates">'+esc(dateOnly(item.signedAt))+' → '+esc(dateOnly(item.expiresAt))+'</div></div>'+StatusBadge(label,key)+'</div>'}).join('');return Panel({header:SectionHeader('Contract History','Previous agreements remain available after renewal.'),body:history?'<div class="data-list">'+history+'</div>':EmptyState('No contract history found.')})}
function AgreementRow(env){const name=primaryAgreementName(env);const main='<div class="data-row-main"><span class="file-mark" aria-hidden="true">PDF</span><div class="data-row-copy"><div class="data-row-title">'+esc(name)+'</div><div class="data-row-subtitle">Completed '+esc(date(env.completedAt))+'</div><div class="agreement-type"><strong>Signed Agreement</strong> · '+env.documentCount+' document'+(env.documentCount===1?'':'s')+'</div></div></div>';return DataRow({href:'/documents/envelopes/'+encodeURIComponent(env.envelopeId),ariaLabel:'Open '+name,main,tail:'<span class="chevron" aria-hidden="true">›</span>'})}
function DocumentsPanel(envelopes){const toolbar='<div class="toolbar">'+SearchInput('document-search','Search documents...','Search completed documents')+SelectControl('document-sort','Sort completed documents',[{value:'newest',label:'Newest Completed'},{value:'oldest',label:'Oldest Completed'},{value:'name',label:'Document Name'}])+'</div>';return Panel({header:SectionHeader('Documents & Agreements','Completed agreements and supporting documents.',toolbar),body:'<div id="agreement-results">'+(envelopes.length?'<div class="data-list">'+envelopes.map(AgreementRow).join('')+'</div>':EmptyState('No completed documents for this representative.'))+'</div>'})}
function renderAgreementResults(envelopes){document.querySelector('#agreement-results').innerHTML=envelopes.length?'<div class="data-list">'+envelopes.map(AgreementRow).join('')+'</div>':EmptyState('No completed documents for this representative.')}
async function repPage(repId){const endpoint='/api/reps/'+encodeURIComponent(repId)+'/envelopes';const data=await api(endpoint);const contract=data.contract;const status=contract?.currentTier?contractStatus(contract.daysRemaining):undefined;const badges='<div class="profile-badges">'+(contract?.currentTier?StatusBadge(contract.contractType||'Unknown','contract')+StatusBadge(status.label,status.key)+StatusBadge('Tier '+contract.currentTier,'tier'):StatusBadge('No Contract','neutral'))+'</div>';const header=PageHeader({breadcrumbs:Breadcrumbs([{label:'Representatives',href:'/documents#representatives'},{label:data.rep.name}]),identity:{name:data.rep.name,email:data.rep.email||(data.rep.type==='requires_resolution'?'Signer identity requires review':'No completed signer resolved'),badges}});const tabs=Tabs([{id:'overview',label:'Overview'},{id:'history',label:'Contract History'},{id:'documents',label:'Documents'}]);app.innerHTML=header+tabs+'<section class="tab-panel" id="panel-overview" role="tabpanel" aria-labelledby="tab-overview">'+CurrentContractPanel(contract)+'</section><section class="tab-panel" id="panel-history" role="tabpanel" aria-labelledby="tab-history" hidden>'+ContractHistoryPanel(contract)+'</section><section class="tab-panel" id="panel-documents" role="tabpanel" aria-labelledby="tab-documents" hidden>'+DocumentsPanel(data.envelopes)+'</section>';initTabs();const load=async()=>{const query=new URLSearchParams({search:document.querySelector('#document-search').value,sort:document.querySelector('#document-sort').value});renderAgreementResults((await api(endpoint+'?'+query)).envelopes)};document.querySelector('#document-search').addEventListener('input',load);document.querySelector('#document-sort').addEventListener('change',load)}
function DocumentRow(envelopeId,document){const presentation=documentPresentation(document.classification);const size=formatFileSize(document.bytes);const base='/api/docusign/envelopes/'+encodeURIComponent(envelopeId)+'/documents/'+encodeURIComponent(document.documentId);const main='<div class="data-row-main"><span class="file-mark" aria-hidden="true">PDF</span><div class="data-row-copy"><div class="data-row-title">'+esc(document.name)+'</div><div class="document-meta">'+StatusBadge(presentation.badge,presentation.key)+'<span>'+esc(presentation.heading)+(size?' · '+esc(size):'')+'</span></div></div></div>';const actions='<div class="document-actions">'+PrimaryButton('View PDF',base,'View '+document.name,true)+SecondaryButton('Download',base+'?download=true','Download '+document.name)+'</div>';return '<article class="data-row document-row'+(presentation.key==='signed'?' is-signed':'')+'">'+main+actions+'</article>'}
function MetadataList(items){return '<dl class="metadata-list">'+items.map(item=>'<div><dt class="metadata-label">'+esc(item.label)+'</dt><dd class="metadata-value'+(item.technical?' technical':'')+'">'+esc(item.value)+'</dd></div>').join('')+'</dl>'}
function DetailsDisclosure(items){return '<details class="details-disclosure"><summary>Advanced Details</summary>'+MetadataList(items)+'</details>'}
async function agreementPage(envelopeId){const env=await api('/api/docusign/envelopes/'+encodeURIComponent(envelopeId));const repId=env.rep?.repId||'unassigned';let repName=env.rep?.name||'Representative';if(repId.includes('@')){try{const repData=await api('/api/reps/'+encodeURIComponent(repId)+'/envelopes');repName=repData.rep?.name||repName}catch{}}const title=primaryAgreementName(env);const order={signed_document:0,supplemental:1,certificate:2};const documents=[...(env.documents||[])].sort((a,b)=>(order[a.classification]??1)-(order[b.classification]??1));const header=PageHeader({breadcrumbs:Breadcrumbs([{label:'Documents',href:'/documents#representatives'},{label:repName,href:'/documents/reps/'+encodeURIComponent(repId)},{label:title}]),title,description:'Completed '+date(env.completedAt)});const documentPanel=Panel({header:SectionHeader('Documents','Signed agreement files and supporting records.'),body:documents.length?'<div class="data-list">'+documents.map(document=>DocumentRow(envelopeId,document)).join('')+'</div>':EmptyState('No documents found for this agreement.')});const details=DetailsDisclosure([{label:'Envelope ID',value:env.envelopeId,technical:true},{label:'Sender',value:env.sender?.email||'Unknown sender'},{label:'Completed At',value:date(env.completedAt)},{label:'Document Count',value:String(env.documentCount??documents.length)}]);app.innerHTML=header+documentPanel+details}
function scrollToHash(){const target=location.hash&&document.querySelector(location.hash);if(target)requestAnimationFrame(()=>target.scrollIntoView({block:'start'}))}
function showError(error){app.innerHTML='<div class="error" role="alert">'+esc(error.message)+'</div>'}
const path=location.pathname;
Promise.resolve().then(()=>{let match;if(path==='/documents'||path==='/documents/')return dashboardPage();if(match=path.match(new RegExp('^/documents/reps/([^/]+)$')))return repPage(decodeURIComponent(match[1]));if(match=path.match(new RegExp('^/documents/envelopes/([^/]+)$')))return agreementPage(decodeURIComponent(match[1]));throw new Error('Page not found')}).catch(showError);
</script></body></html>`;
