export function dashboardSummary(reps = []) {
  const tracked = reps.filter((rep) => rep.contract?.currentContract && rep.contract?.currentTier);
  const active = tracked.filter((rep) => rep.contract.daysRemaining > 0);
  return {
    activeReps: active.length,
    tier1: active.filter((rep) => rep.contract.currentTier === 1).length,
    renewalsDueSoon: active.filter((rep) => rep.contract.daysRemaining > 0 && rep.contract.daysRemaining <= 30).length,
    expired: tracked.filter((rep) => rep.contract.daysRemaining <= 0).length,
  };
}

export function attentionContracts(reps = []) {
  return reps
    .filter((rep) => rep.contract?.currentContract && rep.contract.daysRemaining <= 30)
    .sort((a, b) => a.contract.daysRemaining - b.contract.daysRemaining
      || String(a.name || '').localeCompare(String(b.name || '')));
}

export function upcomingContracts(reps = []) {
  return reps
    .filter((rep) => rep.contract?.currentContract
      && rep.contract.daysRemaining >= 31
      && rep.contract.daysRemaining <= 90)
    .sort((a, b) => a.contract.daysRemaining - b.contract.daysRemaining
      || String(a.name || '').localeCompare(String(b.name || '')));
}

export function contractStatus(daysRemaining) {
  if (daysRemaining <= 0) return { key: 'expired', label: 'Expired', detail: 'Renewal required' };
  if (daysRemaining <= 7) return { key: 'action', label: 'Action Required', detail: 'Renewal is urgent' };
  if (daysRemaining <= 30) return { key: 'renewal', label: 'Renewal Soon', detail: 'Renewal is approaching' };
  return { key: 'active', label: 'Active', detail: 'Contract is current' };
}

export function primaryAgreementName(envelope = {}) {
  return envelope.primaryDocumentName
    || envelope.documents?.find((document) => document.classification === 'signed_document')?.name
    || envelope.documents?.[0]?.name
    || 'Completed Agreement';
}

export function documentPresentation(classification) {
  if (classification === 'signed_document') {
    return { key: 'signed', badge: 'Signed Document', heading: 'Employment Contract' };
  }
  if (classification === 'certificate') {
    return { key: 'certificate', badge: 'Certificate', heading: 'Completion Certificate' };
  }
  return { key: 'supplemental', badge: 'Supplemental', heading: 'Supplemental Document' };
}

export const documentsPage = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="theme-color" content="#124d35">
  <title>Rep Contract Management · Capital Infusion</title>
  <style>
    :root{color-scheme:light;--ink:#17231c;--muted:#647168;--line:#d9e2dc;--paper:#fff;--wash:#f3f7f4;--brand:#145c3c;--brand-dark:#0e452d;--brand-soft:#e7f3eb;--amber:#8a5a18;--amber-soft:#fff5df;--red:#9f2f29;--red-soft:#fff0ee;--gray-soft:#eef2ef;--shadow:0 12px 32px rgb(20 55 36/.07)}
    *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--wash);color:var(--ink);font:15px/1.55 ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
    a{color:inherit}.skip-link{position:fixed;left:16px;top:-60px;z-index:10;background:var(--brand-dark);color:#fff;padding:10px 14px;border-radius:8px}.skip-link:focus{top:16px}
    main{width:min(1120px,calc(100% - 32px));margin:0 auto;padding:42px 0 80px}.page-header{margin-bottom:30px}.eyebrow{color:var(--brand);font-size:12px;font-weight:800;letter-spacing:.11em;text-transform:uppercase}.eyebrow-mark{display:inline-block;width:8px;height:8px;margin-right:8px;border-radius:50%;background:var(--brand);vertical-align:1px}
    h1{max-width:760px;margin:8px 0 10px;font-size:clamp(30px,5vw,48px);font-weight:760;letter-spacing:-.035em;line-height:1.05}h2{margin:0;font-size:21px;letter-spacing:-.015em}h3{margin:0;font-size:17px}.subtle,.meta{color:var(--muted)}.page-intro{max-width:680px;font-size:16px}
    .back{display:inline-flex;align-items:center;gap:7px;margin-bottom:22px;color:var(--brand);font-weight:700;text-decoration:none}.back:hover{text-decoration:underline}.back:focus-visible,.card-link:focus-visible,.button:focus-visible,.toolbar-control:focus-visible,summary:focus-visible{outline:3px solid #75aa8c;outline-offset:3px}
    .section{margin-top:34px}.section-heading{display:flex;align-items:end;justify-content:space-between;gap:16px;margin-bottom:14px}.section-heading p{margin:4px 0 0;color:var(--muted)}.sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}
    .summary-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:13px}.summary-card{min-height:124px;padding:19px;background:var(--paper);border:1px solid var(--line);border-radius:16px;box-shadow:0 2px 8px rgb(20 55 36/.035)}.summary-label{display:block;color:var(--muted);font-size:13px;font-weight:700}.summary-value{display:block;margin-top:14px;font-size:34px;font-weight:780;line-height:1;color:var(--brand-dark)}.summary-note{display:block;margin-top:8px;color:var(--muted);font-size:12px}
    .grid{display:grid;gap:12px}.two-column{grid-template-columns:repeat(2,minmax(0,1fr))}.card{background:var(--paper);border:1px solid var(--line);border-radius:14px;padding:20px;box-shadow:0 1px 3px rgb(20 55 36/.04)}.card-link{display:block;text-decoration:none;transition:border-color .16s ease,box-shadow .16s ease,transform .16s ease}.card-link:hover{border-color:#97b5a3;box-shadow:var(--shadow);transform:translateY(-1px)}
    .attention-card{position:relative;border-left:5px solid var(--amber);padding-left:17px}.attention-card.status-expired,.attention-card.status-action{border-left-color:var(--red)}.attention-top,.card-row,.document-row,.history-row{display:flex;align-items:flex-start;justify-content:space-between;gap:20px}.attention-meta{display:flex;gap:18px;align-items:center;margin-top:12px}.attention-meta strong{font-size:15px}.link-label{display:inline-flex;align-items:center;gap:5px;margin-top:14px;color:var(--brand);font-size:13px;font-weight:750}.chevron{font-size:20px;line-height:1;color:var(--brand);font-weight:500}
    .status-badge{display:inline-flex;align-items:center;border-radius:999px;padding:4px 10px;font-size:12px;font-weight:800;white-space:nowrap}.status-active,.status-tier,.status-signed{background:var(--brand-soft);color:var(--brand-dark)}.status-renewal,.status-certificate{background:var(--amber-soft);color:var(--amber)}.status-action,.status-expired{background:var(--red-soft);color:var(--red)}.status-neutral,.status-supplemental{background:var(--gray-soft);color:#526057}
    .empty{padding:22px 24px;border:1px dashed #b9c7bd;border-radius:14px;background:rgb(255 255 255/.55);color:var(--muted)}.error{padding:16px;border:1px solid #f0c6c2;border-radius:12px;background:var(--red-soft);color:var(--red)}
    .toolbar{display:flex;gap:11px;margin:16px 0 18px;flex-wrap:wrap}.toolbar-control{border:1px solid var(--line);background:var(--paper);border-radius:10px;padding:11px 13px;font:inherit;color:inherit}.toolbar input{flex:1;min-width:230px}.toolbar select{min-width:190px}
    .rep-card{padding:0}.rep-card-inner{display:grid;grid-template-columns:minmax(0,1.5fr) minmax(210px,.8fr) auto;gap:22px;align-items:center;padding:20px}.rep-name{font-size:18px;font-weight:780}.rep-email{margin-top:2px;color:var(--muted);overflow-wrap:anywhere}.badge-row{display:flex;gap:7px;flex-wrap:wrap;margin-top:12px}.rep-facts{display:grid;gap:3px}.rep-count{margin-top:7px;color:var(--muted);font-size:13px}.rep-chevron{align-self:center;padding-right:3px}
    .contract-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin:24px 0}.contract-stat{background:var(--paper);border:1px solid var(--line);border-radius:13px;padding:17px}.contract-stat strong{display:block;margin-top:5px;font-size:19px}.status-panel{display:flex;align-items:center;justify-content:space-between;gap:20px;padding:20px;border-radius:14px;border:1px solid var(--line);background:var(--paper)}.status-panel.status-renewal{border-color:#ebd09d;background:#fffbf2}.status-panel.status-action,.status-panel.status-expired{border-color:#efc7c3;background:#fff8f7}.status-panel-title{font-size:17px;font-weight:780}.status-panel-detail{margin-top:2px;color:var(--muted)}
    .history-list{display:grid;gap:10px}.history-row{align-items:center}.history-dates{margin-top:4px;color:var(--muted)}
    .agreement-card{padding:0}.agreement-inner{display:grid;grid-template-columns:minmax(0,1fr) auto auto;gap:20px;align-items:center;padding:19px}.agreement-name{font-size:16px;font-weight:760}.agreement-meta{margin-top:4px;color:var(--muted)}.agreement-count{color:var(--muted);font-size:13px;white-space:nowrap}
    details.advanced{margin:22px 0 28px;border:1px solid var(--line);border-radius:13px;background:var(--paper)}details.advanced summary{padding:15px 18px;cursor:pointer;color:var(--brand);font-weight:750}details.advanced[open] summary{border-bottom:1px solid var(--line)}.advanced-grid{display:grid;grid-template-columns:1fr 2fr;gap:16px;padding:18px}.technical{font:12px/1.5 ui-monospace,SFMono-Regular,Consolas,monospace;color:var(--muted);overflow-wrap:anywhere}
    .document-list{display:grid;gap:12px}.document-row{align-items:center}.document-heading{color:var(--muted);font-size:12px;font-weight:800;letter-spacing:.07em;text-transform:uppercase}.document-name{margin:4px 0 10px;font-size:17px;font-weight:760}.actions{display:flex;gap:8px}.button{display:inline-flex;align-items:center;justify-content:center;min-width:88px;border:1px solid var(--brand);border-radius:9px;padding:9px 13px;color:var(--brand);text-decoration:none;font-weight:750}.button:hover{background:var(--brand-soft)}.button.primary{background:var(--brand);color:#fff}.button.primary:hover{background:var(--brand-dark)}
    @media(max-width:840px){.summary-grid,.contract-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.two-column{grid-template-columns:1fr}.rep-card-inner{grid-template-columns:minmax(0,1fr) auto}.rep-facts{grid-column:1}.rep-chevron{grid-column:2;grid-row:1/3}.agreement-inner{grid-template-columns:minmax(0,1fr) auto}.agreement-count{grid-column:1}.agreement-inner>.chevron{grid-column:2;grid-row:1/3}}
    @media(max-width:560px){main{width:min(100% - 22px,1120px);padding:26px 0 58px}.summary-grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.summary-card{min-height:108px;padding:15px}.summary-value{font-size:29px}.contract-grid{grid-template-columns:1fr 1fr}.card{padding:17px}.attention-top,.card-row,.document-row,.history-row,.status-panel{display:block}.attention-top .status-badge,.history-row .status-badge{margin-top:10px}.attention-meta{display:block}.attention-meta>*{display:block;margin-top:5px}.rep-card,.agreement-card{padding:0}.rep-card-inner,.agreement-inner{padding:17px}.document-row .actions{margin-top:16px}.actions{display:grid;grid-template-columns:1fr 1fr}.button{width:100%}.advanced-grid{grid-template-columns:1fr}.toolbar>*{width:100%;min-width:0!important}}
  </style>
</head>
<body><a class="skip-link" href="#app">Skip to main content</a><main id="app"><div class="subtle" role="status">Loading contract dashboard…</div></main>
<script>
${dashboardSummary}
${attentionContracts}
${upcomingContracts}
${contractStatus}
${primaryAgreementName}
${documentPresentation}
const app=document.querySelector('#app');
const esc=(value='')=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=value=>value?new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'Unknown';
const dateOnly=value=>value?new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeZone:'UTC'}).format(new Date(value)):'Unknown';
async function api(path){const response=await fetch(path);const body=await response.json();if(!response.ok)throw new Error(body.error||'Request failed');return body}
function shell(title,subtitle,content,back){app.innerHTML=(back?'<a class="back" href="'+back.href+'" aria-label="'+esc(back.label)+'">← '+esc(back.text)+'</a>':'')+'<header class="page-header"><div class="eyebrow"><span class="eyebrow-mark" aria-hidden="true"></span>Capital Infusion</div><h1>'+esc(title)+'</h1><div class="subtle page-intro">'+esc(subtitle)+'</div></header>'+content}
function showError(error){app.innerHTML='<div class="error" role="alert">'+esc(error.message)+'</div>'}
function remainingLabel(days){if(days===0)return 'Expires today';if(days<0)return 'Expired '+Math.abs(days)+' day'+(Math.abs(days)===1?'':'s')+' ago';return days+' day'+(days===1?'':'s')+' remaining'}
function tierTransition(contract){return contract.nextTier?'Tier '+contract.currentTier+' → Tier '+contract.nextTier:'Tier '+contract.currentTier}
function badge(label,key){return '<span class="status-badge status-'+key+'">'+esc(label)+'</span>'}
function summaryMarkup(reps){const values=dashboardSummary(reps);const cards=[['Active Reps',values.activeReps,'With a tracked contract'],['Tier 1',values.tier1,'Active first-tier contracts'],['Renewals Due Soon',values.renewalsDueSoon,'Within the next 30 days'],['Expired',values.expired,'Renewal required']];return '<section aria-labelledby="summary-title"><h2 id="summary-title" class="sr-only">Contract summary</h2><div class="summary-grid">'+cards.map(item=>'<article class="summary-card"><span class="summary-label">'+item[0]+'</span><strong class="summary-value">'+item[1]+'</strong><span class="summary-note">'+item[2]+'</span></article>').join('')+'</div></section>'}
function renewalCard(rep){const contract=rep.contract;const status=contractStatus(contract.daysRemaining);return '<a class="card card-link attention-card status-'+status.key+'" href="/documents/reps/'+encodeURIComponent(rep.repId)+'" aria-label="View '+esc(rep.name)+' contract"><div class="attention-top"><div><h3>'+esc(rep.name)+'</h3><div class="meta">'+esc(tierTransition(contract))+'</div></div>'+badge(status.label,status.key)+'</div><div class="attention-meta"><strong>'+esc(remainingLabel(contract.daysRemaining))+'</strong><span>'+esc(dateOnly(contract.expiresAt))+'</span></div><span class="link-label">View rep <span class="chevron" aria-hidden="true">›</span></span></a>'}
function renewalSections(reps){const attention=attentionContracts(reps);const upcoming=upcomingContracts(reps);return '<section class="section" aria-labelledby="attention-title"><div class="section-heading"><div><h2 id="attention-title">Needs Attention</h2><p>Expired contracts and renewals due within 30 days.</p></div></div>'+(attention.length?'<div class="grid two-column">'+attention.map(renewalCard).join('')+'</div>':'<div class="empty">No contracts currently require action.</div>')+'</section><section class="section" aria-labelledby="upcoming-title"><div class="section-heading"><div><h2 id="upcoming-title">Upcoming Renewals</h2><p>Active contracts expiring in 31–90 days.</p></div></div>'+(upcoming.length?'<div class="grid two-column">'+upcoming.map(renewalCard).join('')+'</div>':'<div class="empty">No upcoming renewals.</div>')+'</section>'}
function repBadges(contract){if(!contract?.currentTier)return '<div class="badge-row">'+badge('No Contract','neutral')+'</div>';const status=contractStatus(contract.daysRemaining);return '<div class="badge-row">'+badge('Tier '+contract.currentTier,'tier')+badge(status.label,status.key)+'</div>'}
function repCard(rep){const email=rep.email||(rep.type==='requires_resolution'?'Multiple completed signers':'No completed signer resolved');const facts=rep.contract?.currentTier?'<strong>Expires '+esc(dateOnly(rep.contract.expiresAt))+'</strong><span class="meta">'+esc(remainingLabel(rep.contract.daysRemaining))+'</span>':'<strong>No tracked contract</strong><span class="meta">Contract lifecycle unavailable</span>';return '<a class="card card-link rep-card" href="/documents/reps/'+encodeURIComponent(rep.repId)+'" aria-label="View '+esc(rep.name)+' contract details"><div class="rep-card-inner"><div><div class="rep-name">'+esc(rep.name)+'</div><div class="rep-email">'+esc(email)+'</div>'+repBadges(rep.contract)+'</div><div class="rep-facts">'+facts+'<span class="rep-count">'+rep.completedEnvelopeCount+' completed agreement'+(rep.completedEnvelopeCount===1?'':'s')+'</span></div><span class="chevron rep-chevron" aria-hidden="true">›</span></div></a>'}
function renderRepResults(reps){document.querySelector('#results').innerHTML=reps.length?reps.map(repCard).join(''):'<div class="empty">No reps found.</div>'}
async function repsPage(){const initial=await api('/api/reps?sort=recent');shell('Rep Contract Management','Track active reps, contract renewals, and completed agreements.',summaryMarkup(initial.reps)+renewalSections(initial.reps)+'<section class="section" aria-labelledby="reps-title"><div class="section-heading"><div><h2 id="reps-title">All Representatives</h2><p>Review contract status and completed agreements.</p></div></div><div class="toolbar"><label class="sr-only" for="search">Search reps by name or email</label><input class="toolbar-control" id="search" type="search" placeholder="Search reps by name or email"><label class="sr-only" for="sort">Sort representatives</label><select class="toolbar-control" id="sort"><option value="recent">Recent activity</option><option value="name">Rep name</option><option value="count">Agreement count</option><option value="expiration">Contract expiration</option></select></div><div id="results" class="grid"></div></section>');renderRepResults(initial.reps);const load=async()=>{const query=new URLSearchParams({search:document.querySelector('#search').value,sort:document.querySelector('#sort').value});const result=await api('/api/reps?'+query);renderRepResults(result.reps)};document.querySelector('#search').addEventListener('input',load);document.querySelector('#sort').addEventListener('change',load)}
function contractDetails(contract){if(!contract?.currentTier)return '<div class="empty">No tracked contract is available for this representative.</div>';const status=contractStatus(contract.daysRemaining);const history=(contract.contracts||[]).map(item=>{const current=item.envelopeId===contract.currentContract?.envelopeId;const expired=current&&contract.daysRemaining<=0;const label=current?(expired?'Expired':'Active'):'Renewed';const key=expired?'expired':current?'active':'neutral';return '<article class="card history-row"><div><strong>Tier '+item.tier+'</strong><div class="history-dates">'+esc(dateOnly(item.signedAt))+' → '+esc(dateOnly(item.expiresAt))+'</div></div>'+badge(label,key)+'</article>'}).join('');return '<section aria-labelledby="lifecycle-title"><h2 id="lifecycle-title" class="sr-only">Contract lifecycle</h2><div class="contract-grid"><article class="contract-stat"><span class="meta">Current Tier</span><strong>Tier '+contract.currentTier+'</strong></article><article class="contract-stat"><span class="meta">Contract Signed</span><strong>'+esc(dateOnly(contract.signedAt))+'</strong></article><article class="contract-stat"><span class="meta">Contract Expires</span><strong>'+esc(dateOnly(contract.expiresAt))+'</strong></article><article class="contract-stat"><span class="meta">Next Tier</span><strong>'+(contract.nextTier?'Tier '+contract.nextTier:'—')+'</strong></article></div><article class="status-panel status-'+status.key+'"><div><div class="status-panel-title">Contract Status</div><div class="status-panel-detail">'+esc(status.detail)+'</div></div><div><strong>'+esc(status.label)+'</strong><div class="meta">'+esc(remainingLabel(contract.daysRemaining))+'</div></div></article></section><section class="section" aria-labelledby="history-title"><div class="section-heading"><div><h2 id="history-title">Contract History</h2><p>Signed agreements remain available after renewal.</p></div></div><div class="history-list">'+(history||'<div class="empty">No contract history found.</div>')+'</div></section>'}
function agreementCard(env){return '<a class="card card-link agreement-card" href="/documents/envelopes/'+encodeURIComponent(env.envelopeId)+'" aria-label="Open '+esc(primaryAgreementName(env))+'"><div class="agreement-inner"><div><div class="agreement-name">'+esc(primaryAgreementName(env))+'</div><div class="agreement-meta">Completed '+esc(date(env.completedAt))+'</div></div><span class="agreement-count">'+env.documentCount+' document'+(env.documentCount===1?'':'s')+'</span><span class="chevron" aria-hidden="true">›</span></div></a>'}
async function repPage(repId){const endpoint='/api/reps/'+encodeURIComponent(repId)+'/envelopes';const data=await api(endpoint);shell(data.rep.name,data.rep.email||(data.rep.type==='requires_resolution'?'Multiple completed signers require resolution':'No completed signer resolved'),contractDetails(data.contract)+'<section class="section" aria-labelledby="agreements-title"><div class="section-heading"><div><h2 id="agreements-title">Documents &amp; Agreements</h2><p>Completed agreements and supporting documents.</p></div></div><div class="toolbar"><label class="sr-only" for="search">Search documents</label><input class="toolbar-control" id="search" type="search" placeholder="Search documents or completion date"><label class="sr-only" for="sort">Sort documents</label><select class="toolbar-control" id="sort"><option value="newest">Newest completed</option><option value="oldest">Oldest completed</option><option value="name">Document name</option></select></div><div id="results" class="grid"></div></section>',{href:'/documents',text:'All Reps',label:'Return to all representatives'});const render=envelopes=>{document.querySelector('#results').innerHTML=envelopes.length?envelopes.map(agreementCard).join(''):'<div class="empty">No completed documents for this rep.</div>'};render(data.envelopes);const load=async()=>{const query=new URLSearchParams({search:document.querySelector('#search').value,sort:document.querySelector('#sort').value});render((await api(endpoint+'?'+query)).envelopes)};document.querySelector('#search').addEventListener('input',load);document.querySelector('#sort').addEventListener('change',load)}
function documentCard(envelopeId,doc){const presentation=documentPresentation(doc.classification);const base='/api/docusign/envelopes/'+encodeURIComponent(envelopeId)+'/documents/'+encodeURIComponent(doc.documentId);return '<article class="card document-row"><div><div class="document-heading">'+presentation.heading+'</div><div class="document-name">'+esc(doc.name)+'</div>'+badge(presentation.badge,presentation.key)+'</div><div class="actions"><a class="button primary" target="_blank" rel="noopener" href="'+base+'" aria-label="View '+esc(doc.name)+'">View</a><a class="button" href="'+base+'?download=true" aria-label="Download '+esc(doc.name)+'">Download</a></div></article>'}
async function envelopePage(envelopeId){const env=await api('/api/docusign/envelopes/'+encodeURIComponent(envelopeId));const title=primaryAgreementName(env);const order={signed_document:0,supplemental:1,certificate:2};const documents=[...(env.documents||[])].sort((a,b)=>(order[a.classification]??1)-(order[b.classification]??1));const docs=documents.map(doc=>documentCard(envelopeId,doc)).join('');const repId=env.rep?.repId||'unassigned';let repName=env.rep?.name||'Representative';if(repId.includes('@')){try{const repData=await api('/api/reps/'+encodeURIComponent(repId)+'/envelopes');repName=repData.rep?.name||repName}catch{}}const details='<details class="advanced"><summary>Advanced Details</summary><div class="advanced-grid"><div><div class="meta">Sent by</div><strong>'+esc(env.sender?.email||'Unknown sender')+'</strong></div><div><div class="meta">Envelope ID</div><div class="technical">'+esc(env.envelopeId)+'</div></div></div></details>';shell(title,repName+' · Completed '+date(env.completedAt),details+'<section class="section" aria-labelledby="documents-title"><div class="section-heading"><div><h2 id="documents-title">Agreement Documents</h2><p>Signed agreement files and supporting records.</p></div></div><div class="document-list">'+(docs||'<div class="empty">No documents found for this agreement.</div>')+'</div></section>',{href:'/documents/reps/'+encodeURIComponent(repId),text:repName,label:'Return to '+repName})}
const path=location.pathname;
Promise.resolve().then(()=>{let match;if(path==='/documents'||path==='/documents/')return repsPage();if(match=path.match(new RegExp('^/documents/reps/([^/]+)$')))return repPage(decodeURIComponent(match[1]));if(match=path.match(new RegExp('^/documents/envelopes/([^/]+)$')))return envelopePage(decodeURIComponent(match[1]));throw new Error('Page not found')}).catch(showError);
</script></body></html>`;
